package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Credit generated by hbm2java
 */
@Entity
@Table(name = "credit", catalog = "erp")
public class Credit implements java.io.Serializable {

	private Integer credId;
	private Dealer dealer;
	private Transaction transaction;
	private String voucherNo;
	private int typeOfPayment;
	private BigDecimal sgst;
	private BigDecimal igst;
	private BigDecimal cgst;
	private BigDecimal otherTax;
	private Date strdte;
	private Date enddte;
	private String particulars;
	private String remarks;
	private char sta;
	private Integer purId;
	private int audUsrId;

	public Credit() {
	}

	public Credit(Transaction transaction, String voucherNo, int typeOfPayment, Date strdte, Date enddte,
			String particulars, String remarks, char sta, int audUsrId) {
		this.transaction = transaction;
		this.voucherNo = voucherNo;
		this.typeOfPayment = typeOfPayment;
		this.strdte = strdte;
		this.enddte = enddte;
		this.particulars = particulars;
		this.remarks = remarks;
		this.sta = sta;
		this.audUsrId = audUsrId;
	}

	public Credit(Dealer dealer, Transaction transaction, String voucherNo, int typeOfPayment, BigDecimal sgst,
			BigDecimal igst, BigDecimal cgst, BigDecimal otherTax, Date strdte, Date enddte, String particulars,
			String remarks, char sta, Integer purId, int audUsrId) {
		this.dealer = dealer;
		this.transaction = transaction;
		this.voucherNo = voucherNo;
		this.typeOfPayment = typeOfPayment;
		this.sgst = sgst;
		this.igst = igst;
		this.cgst = cgst;
		this.otherTax = otherTax;
		this.strdte = strdte;
		this.enddte = enddte;
		this.particulars = particulars;
		this.remarks = remarks;
		this.sta = sta;
		this.purId = purId;
		this.audUsrId = audUsrId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cred_Id", unique = true, nullable = false)
	public Integer getCredId() {
		return this.credId;
	}

	public void setCredId(Integer credId) {
		this.credId = credId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dealer_id")
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	@Column(name = "voucher_no", nullable = false, length = 45)
	public String getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	@Column(name = "type_of_payment", nullable = false)
	public int getTypeOfPayment() {
		return this.typeOfPayment;
	}

	public void setTypeOfPayment(int typeOfPayment) {
		this.typeOfPayment = typeOfPayment;
	}

	@Column(name = "SGST", precision = 10)
	public BigDecimal getSgst() {
		return this.sgst;
	}

	public void setSgst(BigDecimal sgst) {
		this.sgst = sgst;
	}

	@Column(name = "IGST", precision = 10)
	public BigDecimal getIgst() {
		return this.igst;
	}

	public void setIgst(BigDecimal igst) {
		this.igst = igst;
	}

	@Column(name = "CGST", precision = 10)
	public BigDecimal getCgst() {
		return this.cgst;
	}

	public void setCgst(BigDecimal cgst) {
		this.cgst = cgst;
	}

	@Column(name = "OTHER_TAX", precision = 10)
	public BigDecimal getOtherTax() {
		return this.otherTax;
	}

	public void setOtherTax(BigDecimal otherTax) {
		this.otherTax = otherTax;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "strdte", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddte", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "particulars", nullable = false, length = 100)
	public String getParticulars() {
		return this.particulars;
	}

	public void setParticulars(String particulars) {
		this.particulars = particulars;
	}

	@Column(name = "remarks", nullable = false, length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "sta", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "pur_id")
	public Integer getPurId() {
		return this.purId;
	}

	public void setPurId(Integer purId) {
		this.purId = purId;
	}

	@Column(name = "aud_usr_id", nullable = false)
	public int getAudUsrId() {
		return this.audUsrId;
	}

	public void setAudUsrId(int audUsrId) {
		this.audUsrId = audUsrId;
	}

}
