package com.erp.model;
// Generated Jul 15, 2017 12:02:31 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * Dealer generated by hbm2java
 */
@Entity
@Table(name = "dealer", catalog = "erp")
public class Dealer implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer dealerId;
	@JsonView(DataTablesOutput.View.class)
	private String name;
	@JsonView(DataTablesOutput.View.class)
	private String poc;
	@JsonView(DataTablesOutput.View.class)
	private String phnnbr;
	@JsonView(DataTablesOutput.View.class)
	private String email;
	@JsonView(DataTablesOutput.View.class)
	private String adr;
	private Date strdte;
	private Date enddte;
	private char sta;
	private char type;
	private int audUsrId;
	@JsonView(DataTablesOutput.View.class)
	private String gstin;
	@JsonIgnore
	private Set<Product> products = new HashSet<Product>(0);
	@JsonIgnore
	private Set<Credit> credits = new HashSet<Credit>(0);
	@JsonIgnore
	private Set<SaleBill> saleBills = new HashSet<SaleBill>(0);
	@JsonIgnore
	private Set<PurchaseBill> purchaseBills = new HashSet<PurchaseBill>(0);
	@JsonIgnore
	private Set<Debit> debits = new HashSet<Debit>(0);

	public Dealer() {
	}

	public Dealer(String name, String poc, String phnnbr, String email, String adr, Date strdte, Date enddte, char sta,
			char type, int audUsrId, String gstin) {
		this.name = name;
		this.poc = poc;
		this.phnnbr = phnnbr;
		this.email = email;
		this.adr = adr;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.type = type;
		this.audUsrId = audUsrId;
		this.gstin = gstin;
	}

	public Dealer(String name, String poc, String phnnbr, String email, String adr, Date strdte, Date enddte, char sta,
			char type, int audUsrId, String gstin, Set<Product> products, Set<Credit> credits, Set<SaleBill> saleBills,
			Set<PurchaseBill> purchaseBills, Set<Debit> debits) {
		this.name = name;
		this.poc = poc;
		this.phnnbr = phnnbr;
		this.email = email;
		this.adr = adr;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.type = type;
		this.audUsrId = audUsrId;
		this.gstin = gstin;
		this.products = products;
		this.credits = credits;
		this.saleBills = saleBills;
		this.purchaseBills = purchaseBills;
		this.debits = debits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DEALER_ID", unique = true, nullable = false)
	public Integer getDealerId() {
		return this.dealerId;
	}

	public void setDealerId(Integer dealerId) {
		this.dealerId = dealerId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "poc", nullable = false, length = 45)
	public String getPoc() {
		return this.poc;
	}

	public void setPoc(String poc) {
		this.poc = poc;
	}

	@Column(name = "phnnbr", nullable = false, length = 45)
	public String getPhnnbr() {
		return this.phnnbr;
	}

	public void setPhnnbr(String phnnbr) {
		this.phnnbr = phnnbr;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "adr", nullable = false, length = 100)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "strdte", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddte", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "sta", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Column(name = "aud_usr_id", nullable = false)
	public int getAudUsrId() {
		return this.audUsrId;
	}

	public void setAudUsrId(int audUsrId) {
		this.audUsrId = audUsrId;
	}

	@Column(name = "gstin", nullable = false, length = 45)
	public String getGstin() {
		return this.gstin;
	}

	public void setGstin(String gstin) {
		this.gstin = gstin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealer")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealer")
	public Set<Credit> getCredits() {
		return this.credits;
	}

	public void setCredits(Set<Credit> credits) {
		this.credits = credits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealer")
	public Set<SaleBill> getSaleBills() {
		return this.saleBills;
	}

	public void setSaleBills(Set<SaleBill> saleBills) {
		this.saleBills = saleBills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealer")
	public Set<PurchaseBill> getPurchaseBills() {
		return this.purchaseBills;
	}

	public void setPurchaseBills(Set<PurchaseBill> purchaseBills) {
		this.purchaseBills = purchaseBills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dealer")
	public Set<Debit> getDebits() {
		return this.debits;
	}

	public void setDebits(Set<Debit> debits) {
		this.debits = debits;
	}

	@Override
	public String toString() {
		return "Dealer [dealerId=" + dealerId + ", name=" + name + ", poc=" + poc + ", phnnbr=" + phnnbr + ", email="
				+ email + ", adr=" + adr + ", strdte=" + strdte + ", enddte=" + enddte + ", sta=" + sta + ", type="
				+ type + ", audUsrId=" + audUsrId + ", gstin=" + gstin + ", products=" + products + "]";
	}
	

}
