package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logistic generated by hbm2java
 */
@Entity
@Table(name = "logistic", catalog = "erp")
public class Logistic implements java.io.Serializable {

	private Integer logId;
	private String logisticName;
	private String transmitFrom;
	private String transmitTwo;
	private String trackingNumber;
	private String contactPerson;
	private String contactNumber;
	private Integer usrId;
	private String category;
	private Integer refId;
	private Character sta;
	private Date startDate;
	private Date endDate;
	private Set<SaleBill> saleBills = new HashSet<SaleBill>(0);
	private Set<PurchaseBill> purchaseBills = new HashSet<PurchaseBill>(0);

	public Logistic() {
	}

	public Logistic(String logisticName, String transmitFrom, String transmitTwo, String trackingNumber,
			String contactPerson, String contactNumber, Integer usrId, String category, Integer refId, Character sta,
			Date startDate, Date endDate, Set<SaleBill> saleBills, Set<PurchaseBill> purchaseBills) {
		this.logisticName = logisticName;
		this.transmitFrom = transmitFrom;
		this.transmitTwo = transmitTwo;
		this.trackingNumber = trackingNumber;
		this.contactPerson = contactPerson;
		this.contactNumber = contactNumber;
		this.usrId = usrId;
		this.category = category;
		this.refId = refId;
		this.sta = sta;
		this.startDate = startDate;
		this.endDate = endDate;
		this.saleBills = saleBills;
		this.purchaseBills = purchaseBills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "LOG_ID", unique = true, nullable = false)
	public Integer getLogId() {
		return this.logId;
	}

	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	@Column(name = "LOGISTIC_NAME", length = 45)
	public String getLogisticName() {
		return this.logisticName;
	}

	public void setLogisticName(String logisticName) {
		this.logisticName = logisticName;
	}

	@Column(name = "TRANSMIT_FROM", length = 45)
	public String getTransmitFrom() {
		return this.transmitFrom;
	}

	public void setTransmitFrom(String transmitFrom) {
		this.transmitFrom = transmitFrom;
	}

	@Column(name = "TRANSMIT_TWO", length = 45)
	public String getTransmitTwo() {
		return this.transmitTwo;
	}

	public void setTransmitTwo(String transmitTwo) {
		this.transmitTwo = transmitTwo;
	}

	@Column(name = "TRACKING_NUMBER", length = 45)
	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	@Column(name = "CONTACT_PERSON", length = 45)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "CONTACT_NUMBER", length = 45)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "USR_ID")
	public Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	@Column(name = "CATEGORY", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "REF_ID")
	public Integer getRefId() {
		return this.refId;
	}

	public void setRefId(Integer refId) {
		this.refId = refId;
	}

	@Column(name = "STA", length = 1)
	public Character getSta() {
		return this.sta;
	}

	public void setSta(Character sta) {
		this.sta = sta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logistic")
	public Set<SaleBill> getSaleBills() {
		return this.saleBills;
	}

	public void setSaleBills(Set<SaleBill> saleBills) {
		this.saleBills = saleBills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logistic")
	public Set<PurchaseBill> getPurchaseBills() {
		return this.purchaseBills;
	}

	public void setPurchaseBills(Set<PurchaseBill> purchaseBills) {
		this.purchaseBills = purchaseBills;
	}

}
