package com.erp.model;
// Generated Jul 12, 2017 11:03:33 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LogisticId generated by hbm2java
 */
@Embeddable
public class LogisticId implements java.io.Serializable {

	private int logId;
	private String logisticName;
	private String transmitFrom;
	private String transmitTwo;
	private String trackingNumber;
	private String contactPerson;
	private String contactNumber;
	private Integer usrId;
	private String category;
	private Integer refId;
	private Character sta;
	private Date startDate;
	private Date endDate;

	public LogisticId() {
	}

	public LogisticId(int logId) {
		this.logId = logId;
	}

	public LogisticId(int logId, String logisticName, String transmitFrom, String transmitTwo, String trackingNumber,
			String contactPerson, String contactNumber, Integer usrId, String category, Integer refId, Character sta,
			Date startDate, Date endDate) {
		this.logId = logId;
		this.logisticName = logisticName;
		this.transmitFrom = transmitFrom;
		this.transmitTwo = transmitTwo;
		this.trackingNumber = trackingNumber;
		this.contactPerson = contactPerson;
		this.contactNumber = contactNumber;
		this.usrId = usrId;
		this.category = category;
		this.refId = refId;
		this.sta = sta;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Column(name = "LOG_ID", nullable = false)
	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	@Column(name = "LOGISTIC_NAME", length = 45)
	public String getLogisticName() {
		return this.logisticName;
	}

	public void setLogisticName(String logisticName) {
		this.logisticName = logisticName;
	}

	@Column(name = "TRANSMIT_FROM", length = 45)
	public String getTransmitFrom() {
		return this.transmitFrom;
	}

	public void setTransmitFrom(String transmitFrom) {
		this.transmitFrom = transmitFrom;
	}

	@Column(name = "TRANSMIT_TWO", length = 45)
	public String getTransmitTwo() {
		return this.transmitTwo;
	}

	public void setTransmitTwo(String transmitTwo) {
		this.transmitTwo = transmitTwo;
	}

	@Column(name = "TRACKING_NUMBER", length = 45)
	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	@Column(name = "CONTACT_PERSON", length = 45)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "CONTACT_NUMBER", length = 45)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	@Column(name = "USR_ID")
	public Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	@Column(name = "CATEGORY", length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "REF_ID")
	public Integer getRefId() {
		return this.refId;
	}

	public void setRefId(Integer refId) {
		this.refId = refId;
	}

	@Column(name = "STA", length = 1)
	public Character getSta() {
		return this.sta;
	}

	public void setSta(Character sta) {
		this.sta = sta;
	}

	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogisticId))
			return false;
		LogisticId castOther = (LogisticId) other;

		return (this.getLogId() == castOther.getLogId())
				&& ((this.getLogisticName() == castOther.getLogisticName())
						|| (this.getLogisticName() != null && castOther.getLogisticName() != null
								&& this.getLogisticName().equals(castOther.getLogisticName())))
				&& ((this.getTransmitFrom() == castOther.getTransmitFrom())
						|| (this.getTransmitFrom() != null && castOther.getTransmitFrom() != null
								&& this.getTransmitFrom().equals(castOther.getTransmitFrom())))
				&& ((this.getTransmitTwo() == castOther.getTransmitTwo())
						|| (this.getTransmitTwo() != null && castOther.getTransmitTwo() != null
								&& this.getTransmitTwo().equals(castOther.getTransmitTwo())))
				&& ((this.getTrackingNumber() == castOther.getTrackingNumber())
						|| (this.getTrackingNumber() != null && castOther.getTrackingNumber() != null
								&& this.getTrackingNumber().equals(castOther.getTrackingNumber())))
				&& ((this.getContactPerson() == castOther.getContactPerson())
						|| (this.getContactPerson() != null && castOther.getContactPerson() != null
								&& this.getContactPerson().equals(castOther.getContactPerson())))
				&& ((this.getContactNumber() == castOther.getContactNumber())
						|| (this.getContactNumber() != null && castOther.getContactNumber() != null
								&& this.getContactNumber().equals(castOther.getContactNumber())))
				&& ((this.getUsrId() == castOther.getUsrId()) || (this.getUsrId() != null
						&& castOther.getUsrId() != null && this.getUsrId().equals(castOther.getUsrId())))
				&& ((this.getCategory() == castOther.getCategory()) || (this.getCategory() != null
						&& castOther.getCategory() != null && this.getCategory().equals(castOther.getCategory())))
				&& ((this.getRefId() == castOther.getRefId()) || (this.getRefId() != null
						&& castOther.getRefId() != null && this.getRefId().equals(castOther.getRefId())))
				&& ((this.getSta() == castOther.getSta()) || (this.getSta() != null && castOther.getSta() != null
						&& this.getSta().equals(castOther.getSta())))
				&& ((this.getStartDate() == castOther.getStartDate()) || (this.getStartDate() != null
						&& castOther.getStartDate() != null && this.getStartDate().equals(castOther.getStartDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this.getEndDate() != null
						&& castOther.getEndDate() != null && this.getEndDate().equals(castOther.getEndDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLogId();
		result = 37 * result + (getLogisticName() == null ? 0 : this.getLogisticName().hashCode());
		result = 37 * result + (getTransmitFrom() == null ? 0 : this.getTransmitFrom().hashCode());
		result = 37 * result + (getTransmitTwo() == null ? 0 : this.getTransmitTwo().hashCode());
		result = 37 * result + (getTrackingNumber() == null ? 0 : this.getTrackingNumber().hashCode());
		result = 37 * result + (getContactPerson() == null ? 0 : this.getContactPerson().hashCode());
		result = 37 * result + (getContactNumber() == null ? 0 : this.getContactNumber().hashCode());
		result = 37 * result + (getUsrId() == null ? 0 : this.getUsrId().hashCode());
		result = 37 * result + (getCategory() == null ? 0 : this.getCategory().hashCode());
		result = 37 * result + (getRefId() == null ? 0 : this.getRefId().hashCode());
		result = 37 * result + (getSta() == null ? 0 : this.getSta().hashCode());
		result = 37 * result + (getStartDate() == null ? 0 : this.getStartDate().hashCode());
		result = 37 * result + (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		return result;
	}

}
