package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "erp")
public class Notification implements java.io.Serializable {

	private Integer notifyId;
	private String notifyDes;
	private String notifyRole;
	private Integer audUsrId;

	public Notification() {
	}

	public Notification(String notifyDes, String notifyRole, Integer audUsrId) {
		this.notifyDes = notifyDes;
		this.notifyRole = notifyRole;
		this.audUsrId = audUsrId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NOTIFY_ID", unique = true, nullable = false)
	public Integer getNotifyId() {
		return this.notifyId;
	}

	public void setNotifyId(Integer notifyId) {
		this.notifyId = notifyId;
	}

	@Column(name = "NOTIFY_DES", length = 45)
	public String getNotifyDes() {
		return this.notifyDes;
	}

	public void setNotifyDes(String notifyDes) {
		this.notifyDes = notifyDes;
	}

	@Column(name = "NOTIFY_ROLE", length = 10)
	public String getNotifyRole() {
		return this.notifyRole;
	}

	public void setNotifyRole(String notifyRole) {
		this.notifyRole = notifyRole;
	}

	@Column(name = "AUD_USR_ID")
	public Integer getAudUsrId() {
		return this.audUsrId;
	}

	public void setAudUsrId(Integer audUsrId) {
		this.audUsrId = audUsrId;
	}

}
