package com.erp.model;
// Generated Jul 15, 2017 12:02:31 AM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "erp")
public class Product implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer prdId;
	@JsonView(DataTablesOutput.View.class)
	private Dealer dealer;
	@JsonView(DataTablesOutput.View.class)
	private String prdnme;
	@JsonView(DataTablesOutput.View.class)
	private Date strdte;
	@JsonView(DataTablesOutput.View.class)
	private Date enddte;
	private char sta;
	@JsonView(DataTablesOutput.View.class)
	private short warranty;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal purAmt;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal saleAmt;
	@JsonView(DataTablesOutput.View.class)
	private String hsnCode;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal sgst;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal igst;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal cgst;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal otherTax;
	private int audUsrId;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal discount;
	@JsonIgnore
	private Set<Sale> sales = new HashSet<Sale>(0);
	@JsonIgnore
	private Set<Purchase> purchases = new HashSet<Purchase>(0);

	public Product() {
	}

	public Product(Dealer dealer, String prdnme, Date strdte, Date enddte, char sta, short warranty, BigDecimal purAmt,
			BigDecimal saleAmt, String hsnCode, int audUsrId) {
		this.dealer = dealer;
		this.prdnme = prdnme;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.warranty = warranty;
		this.purAmt = purAmt;
		this.saleAmt = saleAmt;
		this.hsnCode = hsnCode;
		this.audUsrId = audUsrId;
	}

	public Product(Dealer dealer, String prdnme, Date strdte, Date enddte, char sta, short warranty, BigDecimal purAmt,
			BigDecimal saleAmt, String hsnCode, BigDecimal sgst, BigDecimal igst, BigDecimal cgst, BigDecimal otherTax,
			int audUsrId, BigDecimal discount, Set<Sale> sales, Set<Purchase> purchases) {
		this.dealer = dealer;
		this.prdnme = prdnme;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.warranty = warranty;
		this.purAmt = purAmt;
		this.saleAmt = saleAmt;
		this.hsnCode = hsnCode;
		this.sgst = sgst;
		this.igst = igst;
		this.cgst = cgst;
		this.otherTax = otherTax;
		this.audUsrId = audUsrId;
		this.discount = discount;
		this.sales = sales;
		this.purchases = purchases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRD_ID", unique = true, nullable = false)
	public Integer getPrdId() {
		return this.prdId;
	}

	public void setPrdId(Integer prdId) {
		this.prdId = prdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BLD_ID", nullable = false)
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@Column(name = "PRDNME", nullable = false, length = 45)
	public String getPrdnme() {
		return this.prdnme;
	}

	public void setPrdnme(String prdnme) {
		this.prdnme = prdnme;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "WARRANTY", nullable = false, precision = 3, scale = 0)
	public short getWarranty() {
		return this.warranty;
	}

	public void setWarranty(short warranty) {
		this.warranty = warranty;
	}

	@Column(name = "PUR_AMT", nullable = false, precision = 10)
	public BigDecimal getPurAmt() {
		return this.purAmt;
	}

	public void setPurAmt(BigDecimal purAmt) {
		this.purAmt = purAmt;
	}

	@Column(name = "SALE_AMT", nullable = false, precision = 10)
	public BigDecimal getSaleAmt() {
		return this.saleAmt;
	}

	public void setSaleAmt(BigDecimal saleAmt) {
		this.saleAmt = saleAmt;
	}

	@Column(name = "hsn_code", nullable = false, length = 45)
	public String getHsnCode() {
		return this.hsnCode;
	}

	public void setHsnCode(String hsnCode) {
		this.hsnCode = hsnCode;
	}

	@Column(name = "SGST", precision = 10)
	public BigDecimal getSgst() {
		return this.sgst;
	}

	public void setSgst(BigDecimal sgst) {
		this.sgst = sgst;
	}

	@Column(name = "IGST", precision = 10)
	public BigDecimal getIgst() {
		return this.igst;
	}

	public void setIgst(BigDecimal igst) {
		this.igst = igst;
	}

	@Column(name = "CGST", precision = 10)
	public BigDecimal getCgst() {
		return this.cgst;
	}

	public void setCgst(BigDecimal cgst) {
		this.cgst = cgst;
	}

	@Column(name = "OTHER_TAX", precision = 10)
	public BigDecimal getOtherTax() {
		return this.otherTax;
	}

	public void setOtherTax(BigDecimal otherTax) {
		this.otherTax = otherTax;
	}

	@Column(name = "aud_usr_id", nullable = false)
	public int getAudUsrId() {
		return this.audUsrId;
	}

	public void setAudUsrId(int audUsrId) {
		this.audUsrId = audUsrId;
	}

	@Column(name = "discount", precision = 10)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Sale> getSales() {
		return this.sales;
	}

	public void setSales(Set<Sale> sales) {
		this.sales = sales;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Purchase> getPurchases() {
		return this.purchases;
	}

	public void setPurchases(Set<Purchase> purchases) {
		this.purchases = purchases;
	}

	@Override
	public String toString() {
		return "Product [prdId=" + prdId + ", dealer=" + dealer + ", prdnme=" + prdnme + ", strdte=" + strdte
				+ ", enddte=" + enddte + ", sta=" + sta + ", warranty=" + warranty + ", purAmt=" + purAmt + ", saleAmt="
				+ saleAmt + ", hsnCode=" + hsnCode + ", sgst=" + sgst + ", igst=" + igst + ", cgst=" + cgst
				+ ", otherTax=" + otherTax + ", audUsrId=" + audUsrId + ", discount=" + discount + "]";
	}

	
}
