package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name = "purchase", catalog = "erp")
public class Purchase implements java.io.Serializable {

	private Integer purId;
	private Product product;
	private PurchaseBill purchaseBill;
	private int cnt;
	private Date strdte;
	private Date enddte;
	private char sta;
	private Integer orderNum;
	private BigDecimal purAmt;
	private BigDecimal sgst;
	private BigDecimal igst;
	private BigDecimal cgst;
	private BigDecimal otherTax;
	private int audUsrId;

	public Purchase() {
	}

	public Purchase(Product product, PurchaseBill purchaseBill, int cnt, Date strdte, Date enddte, char sta,
			BigDecimal purAmt, int audUsrId) {
		this.product = product;
		this.purchaseBill = purchaseBill;
		this.cnt = cnt;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.purAmt = purAmt;
		this.audUsrId = audUsrId;
	}

	public Purchase(Product product, PurchaseBill purchaseBill, int cnt, Date strdte, Date enddte, char sta,
			Integer orderNum, BigDecimal purAmt, BigDecimal sgst, BigDecimal igst, BigDecimal cgst, BigDecimal otherTax,
			int audUsrId) {
		this.product = product;
		this.purchaseBill = purchaseBill;
		this.cnt = cnt;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.orderNum = orderNum;
		this.purAmt = purAmt;
		this.sgst = sgst;
		this.igst = igst;
		this.cgst = cgst;
		this.otherTax = otherTax;
		this.audUsrId = audUsrId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PUR_ID", unique = true, nullable = false)
	public Integer getPurId() {
		return this.purId;
	}

	public void setPurId(Integer purId) {
		this.purId = purId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILL_ID", nullable = false)
	public PurchaseBill getPurchaseBill() {
		return this.purchaseBill;
	}

	public void setPurchaseBill(PurchaseBill purchaseBill) {
		this.purchaseBill = purchaseBill;
	}

	@Column(name = "CNT", nullable = false)
	public int getCnt() {
		return this.cnt;
	}

	public void setCnt(int cnt) {
		this.cnt = cnt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "ORDER_NUM")
	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	@Column(name = "PUR_AMT", nullable = false, precision = 10)
	public BigDecimal getPurAmt() {
		return this.purAmt;
	}

	public void setPurAmt(BigDecimal purAmt) {
		this.purAmt = purAmt;
	}

	@Column(name = "SGST", precision = 10)
	public BigDecimal getSgst() {
		return this.sgst;
	}

	public void setSgst(BigDecimal sgst) {
		this.sgst = sgst;
	}

	@Column(name = "IGST", precision = 10)
	public BigDecimal getIgst() {
		return this.igst;
	}

	public void setIgst(BigDecimal igst) {
		this.igst = igst;
	}

	@Column(name = "CGST", precision = 10)
	public BigDecimal getCgst() {
		return this.cgst;
	}

	public void setCgst(BigDecimal cgst) {
		this.cgst = cgst;
	}

	@Column(name = "OTHER_TAX", precision = 10)
	public BigDecimal getOtherTax() {
		return this.otherTax;
	}

	public void setOtherTax(BigDecimal otherTax) {
		this.otherTax = otherTax;
	}

	@Column(name = "aud_usr_id", nullable = false)
	public int getAudUsrId() {
		return this.audUsrId;
	}

	public void setAudUsrId(int audUsrId) {
		this.audUsrId = audUsrId;
	}

}
