package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseBill generated by hbm2java
 */
@Entity
@Table(name = "purchase_bill", catalog = "erp")
public class PurchaseBill implements java.io.Serializable {

	private Integer billId;
	private Dealer dealer;
	private Logistic logistic;
	private User user;
	private Date strdte;
	private char sta;
	private Date enddte;
	private String poNum;
	private Date entryDte;
	private char taxType;
	private Set<Purchase> purchases = new HashSet<Purchase>(0);

	public PurchaseBill() {
	}

	public PurchaseBill(Dealer dealer, User user, Date strdte, char sta, Date enddte,char taxType) {
		this.dealer = dealer;
		this.user = user;
		this.strdte = strdte;
		this.sta = sta;
		this.enddte = enddte;
		this.taxType=taxType;
	}

	public PurchaseBill(Dealer dealer, Logistic logistic, User user, Date strdte, char sta, Date enddte, String poNum,
			Date entryDte, char taxType, Set<Purchase> purchases) {
		this.dealer = dealer;
		this.logistic = logistic;
		this.user = user;
		this.strdte = strdte;
		this.sta = sta;
		this.enddte = enddte;
		this.poNum = poNum;
		this.entryDte = entryDte;
		this.purchases = purchases;
		this.taxType=taxType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BILL_ID", unique = true, nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BLD_ID", nullable = false)
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOG_ID")
	public Logistic getLogistic() {
		return this.logistic;
	}

	public void setLogistic(Logistic logistic) {
		this.logistic = logistic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "po_num", length = 45)
	public String getPoNum() {
		return this.poNum;
	}

	public void setPoNum(String poNum) {
		this.poNum = poNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_dte", length = 10)
	public Date getEntryDte() {
		return this.entryDte;
	}

	public void setEntryDte(Date entryDte) {
		this.entryDte = entryDte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchaseBill")
	public Set<Purchase> getPurchases() {
		return this.purchases;
	}

	public void setPurchases(Set<Purchase> purchases) {
		this.purchases = purchases;
	}

	public char getTaxType() {
		return taxType;
	}

	public void setTaxType(char taxType) {
		this.taxType = taxType;
	}

}
