package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonView;

/**
 * Sale generated by hbm2java
 */
@Entity
@Table(name = "sale", catalog = "erp")
public class Sale implements java.io.Serializable {
	@JsonView(DataTablesOutput.View.class)
	private Integer salId;
	@JsonView(DataTablesOutput.View.class)
	private Product product;
	@JsonView(DataTablesOutput.View.class)
	private SaleBill saleBill;
	@JsonView(DataTablesOutput.View.class)
	private int cnt;
	private char sta;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal saleAmt;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal sgst;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal igst;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal cgst;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal otherTax;
	@JsonView(DataTablesOutput.View.class)
	private BigDecimal discount;
	private int audUsrId;

	public Sale() {
	}

	public Sale(Product product, SaleBill saleBill, int cnt, char sta, BigDecimal saleAmt, int audUsrId) {
		this.product = product;
		this.saleBill = saleBill;
		this.cnt = cnt;
		this.sta = sta;
		this.saleAmt = saleAmt;
		this.audUsrId = audUsrId;
	}

	public Sale(Product product, SaleBill saleBill, int cnt, char sta, BigDecimal saleAmt, BigDecimal sgst,
			BigDecimal igst, BigDecimal cgst, BigDecimal otherTax, BigDecimal discount, int audUsrId) {
		this.product = product;
		this.saleBill = saleBill;
		this.cnt = cnt;
		this.sta = sta;
		this.saleAmt = saleAmt;
		this.sgst = sgst;
		this.igst = igst;
		this.cgst = cgst;
		this.otherTax = otherTax;
		this.discount = discount;
		this.audUsrId = audUsrId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SAL_ID", unique = true, nullable = false)
	public Integer getSalId() {
		return this.salId;
	}

	public void setSalId(Integer salId) {
		this.salId = salId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRD_ID", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILL_ID", nullable = false)
	public SaleBill getSaleBill() {
		return this.saleBill;
	}

	public void setSaleBill(SaleBill saleBill) {
		this.saleBill = saleBill;
	}

	@Column(name = "CNT", nullable = false)
	public int getCnt() {
		return this.cnt;
	}

	public void setCnt(int cnt) {
		this.cnt = cnt;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "SALE_AMT", nullable = false, precision = 10)
	public BigDecimal getSaleAmt() {
		return this.saleAmt;
	}

	public void setSaleAmt(BigDecimal saleAmt) {
		this.saleAmt = saleAmt;
	}

	@Column(name = "SGST", precision = 10)
	public BigDecimal getSgst() {
		return this.sgst;
	}

	public void setSgst(BigDecimal sgst) {
		this.sgst = sgst;
	}

	@Column(name = "IGST", precision = 10)
	public BigDecimal getIgst() {
		return this.igst;
	}

	public void setIgst(BigDecimal igst) {
		this.igst = igst;
	}

	@Column(name = "CGST", precision = 10)
	public BigDecimal getCgst() {
		return this.cgst;
	}

	public void setCgst(BigDecimal cgst) {
		this.cgst = cgst;
	}

	@Column(name = "OTHER_TAX", precision = 10)
	public BigDecimal getOtherTax() {
		return this.otherTax;
	}

	public void setOtherTax(BigDecimal otherTax) {
		this.otherTax = otherTax;
	}

	@Column(name = "discount", precision = 10)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "aud_usr_id", nullable = false)
	public int getAudUsrId() {
		return this.audUsrId;
	}

	public void setAudUsrId(int audUsrId) {
		this.audUsrId = audUsrId;
	}

}
