package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * SaleBill generated by hbm2java
 */
@Entity
@Table(name = "sale_bill", catalog = "erp")
public class SaleBill implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer billId;
	@JsonView(DataTablesOutput.View.class)
	private Dealer dealer;
	@JsonView(DataTablesOutput.View.class)
	private Logistic logistic;
	@JsonView(DataTablesOutput.View.class)
	private User user;
	@JsonView(DataTablesOutput.View.class)
	private Date strdte;
	private char sta;
	private Date enddte;
	@JsonView(DataTablesOutput.View.class)
	private String poNum;
	private Date entryDte;
	private char taxType;
	@JsonIgnore
	private Set<Sale> sales = new HashSet<Sale>(0);

	public SaleBill() {
	}

	public SaleBill(Dealer dealer, User user, Date strdte, char sta, Date enddte,char taxType) {
		this.dealer = dealer;
		this.user = user;
		this.strdte = strdte;
		this.sta = sta;
		this.enddte = enddte;
		this.taxType=taxType;
	}

	public SaleBill(Dealer dealer, Logistic logistic, User user, Date strdte, char sta, Date enddte, String poNum,char taxType,
			Date entryDte, Set<Sale> sales) {
		this.dealer = dealer;
		this.logistic = logistic;
		this.user = user;
		this.strdte = strdte;
		this.sta = sta;
		this.enddte = enddte;
		this.poNum = poNum;
		this.entryDte = entryDte;
		this.sales = sales;
		this.taxType=taxType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BILL_ID", unique = true, nullable = false)
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLI_ID", nullable = false)
	public Dealer getDealer() {
		return this.dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOG_ID")
	public Logistic getLogistic() {
		return this.logistic;
	}

	public void setLogistic(Logistic logistic) {
		this.logistic = logistic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "po_num", length = 45)
	public String getPoNum() {
		return this.poNum;
	}

	public void setPoNum(String poNum) {
		this.poNum = poNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "entry_dte", length = 10)
	public Date getEntryDte() {
		return this.entryDte;
	}

	public void setEntryDte(Date entryDte) {
		this.entryDte = entryDte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "saleBill")
	public Set<Sale> getSales() {
		return this.sales;
	}

	public void setSales(Set<Sale> sales) {
		this.sales = sales;
	}

	public char getTaxType() {
		return taxType;
	}

	public void setTaxType(char taxType) {
		this.taxType = taxType;
	}

	@Override
	public String toString() {
		return "SaleBill [billId=" + billId + ", dealer=" + dealer + ", logistic=" + logistic + ", user=" + user
				+ ", strdte=" + strdte + ", sta=" + sta + ", enddte=" + enddte + ", poNum=" + poNum + ", entryDte="
				+ entryDte + ", taxType=" + taxType + "]";
	}
	

}
