package com.erp.model;
// Generated Jul 17, 2017 12:28:14 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.jpa.datatables.mapping.DataTablesOutput;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "erp")
public class User implements java.io.Serializable {

	@JsonView(DataTablesOutput.View.class)
	private Integer usrId;
	@JsonView(DataTablesOutput.View.class)
	private Branch branch;
	@JsonView(DataTablesOutput.View.class)
	private String usrnme;
	@JsonView(DataTablesOutput.View.class)
	private String phnnbr;
	@JsonView(DataTablesOutput.View.class)
	private String email;
	@JsonView(DataTablesOutput.View.class)
	private String adr;
	private Date strdte;
	private Date enddte;
	private char sta;
	private String pswd;
	private Integer audUsrId;
	@JsonIgnore
	private Set<SaleBill> saleBills = new HashSet<SaleBill>(0);
	@JsonIgnore
	private Set<PurchaseBill> purchaseBills = new HashSet<PurchaseBill>(0);
	@JsonIgnore
	private Set<Role> roles = new HashSet<Role>(0);
	@JsonIgnore
	private Set<Task> tasks = new HashSet<Task>(0);

	public User() {
	}

	public User(Branch branch, String usrnme, String phnnbr, String email, String adr, Date strdte, Date enddte,
			char sta, String pswd) {
		this.branch = branch;
		this.usrnme = usrnme;
		this.phnnbr = phnnbr;
		this.email = email;
		this.adr = adr;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.pswd = pswd;
	}

	public User(Branch branch, String usrnme, String phnnbr, String email, String adr, Date strdte, Date enddte,
			char sta, String pswd, Integer audUsrId, Set<SaleBill> saleBills, Set<PurchaseBill> purchaseBills,
			Set<Role> roles, Set<Task> tasks) {
		this.branch = branch;
		this.usrnme = usrnme;
		this.phnnbr = phnnbr;
		this.email = email;
		this.adr = adr;
		this.strdte = strdte;
		this.enddte = enddte;
		this.sta = sta;
		this.pswd = pswd;
		this.audUsrId = audUsrId;
		this.saleBills = saleBills;
		this.purchaseBills = purchaseBills;
		this.roles = roles;
		this.tasks = tasks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USR_ID", unique = true, nullable = false)
	public Integer getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Integer usrId) {
		this.usrId = usrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BRANCH_ID", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "USRNME", nullable = false, length = 45)
	public String getUsrnme() {
		return this.usrnme;
	}

	public void setUsrnme(String usrnme) {
		this.usrnme = usrnme;
	}

	@Column(name = "PHNNBR", nullable = false, length = 10)
	public String getPhnnbr() {
		return this.phnnbr;
	}

	public void setPhnnbr(String phnnbr) {
		this.phnnbr = phnnbr;
	}

	@Column(name = "EMAIL", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ADR", nullable = false, length = 45)
	public String getAdr() {
		return this.adr;
	}

	public void setAdr(String adr) {
		this.adr = adr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STRDTE", nullable = false, length = 10)
	public Date getStrdte() {
		return this.strdte;
	}

	public void setStrdte(Date strdte) {
		this.strdte = strdte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDTE", nullable = false, length = 10)
	public Date getEnddte() {
		return this.enddte;
	}

	public void setEnddte(Date enddte) {
		this.enddte = enddte;
	}

	@Column(name = "STA", nullable = false, length = 1)
	public char getSta() {
		return this.sta;
	}

	public void setSta(char sta) {
		this.sta = sta;
	}

	@Column(name = "PSWD", nullable = false, length = 45)
	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	@Column(name = "AUD_USR_ID")
	public Integer getAudUsrId() {
		return this.audUsrId;
	}

	public void setAudUsrId(Integer audUsrId) {
		this.audUsrId = audUsrId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<SaleBill> getSaleBills() {
		return this.saleBills;
	}

	public void setSaleBills(Set<SaleBill> saleBills) {
		this.saleBills = saleBills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<PurchaseBill> getPurchaseBills() {
		return this.purchaseBills;
	}

	public void setPurchaseBills(Set<PurchaseBill> purchaseBills) {
		this.purchaseBills = purchaseBills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

	@Override
	public String toString() {
		return "User [usrId=" + usrId + ", branch=" + branch + ", usrnme=" + usrnme + ", phnnbr=" + phnnbr + ", email="
				+ email + ", adr=" + adr + ", strdte=" + strdte + ", enddte=" + enddte + ", sta=" + sta + ", pswd="
				+ pswd + ", audUsrId=" + audUsrId + "]";
	}

	
}
