package com.aakruth.model;
// Generated Jun 9, 2017 11:46:56 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "aakruthdb")
public class Notification implements java.io.Serializable {

	private Integer notId;
	private UsrTbl usrTbl;
	private Date dateTime;
	private String action;

	public Notification() {
	}

	public Notification(UsrTbl usrTbl, Date dateTime, String action) {
		this.usrTbl = usrTbl;
		this.dateTime = dateTime;
		this.action = action;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "not_id", unique = true, nullable = false)
	public Integer getNotId() {
		return this.notId;
	}

	public void setNotId(Integer notId) {
		this.notId = notId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usr_id", nullable = false)
	public UsrTbl getUsrTbl() {
		return this.usrTbl;
	}

	public void setUsrTbl(UsrTbl usrTbl) {
		this.usrTbl = usrTbl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time", nullable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "action", nullable = false, length = 45)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

}
